### ISSUE TITLE
Not work on win 7 x64 ... 

### ISSUE THREAD

**Issue by deltaone** [YatoDev/DirectXOverlay#1]
Even with your removed precompiled binaries ...
Variant with 
           MoveWindow(Handle, X, Y, Width, Height, false); (when moving window)
and (after creating window)
            const int COLOR_MENU = 4;
            int bgColor = GetSysColor(COLOR_MENU);
            SetLayeredWindowAttributes(Handle, (uint)bgColor, 255, 1 | 2);
work ok, any suggestions ?

P.S. Change window class to "#32770", with your window class is impossible to fetch overlay position and dimensions ...

Ported to VS 2010 and SharpDX-SDK-2.6.3
[src.zip](https://github.com/YatoDev/DirectXOverlay/files/743461/src.zip)

**Comment by YatoDev** [comment]
The usage of the desktop window class is intended.
Also the fact that you can't fetch it isn't true. The Wrapper class holds all that information you would need.

I don't know if there is something i can do to provide better compatibility with windows 7.
I heard from most other Overlay's that they also don't work with the Windows 7 Aero mode.

If you have any ideas please contact me.

**Comment by deltaone** [comment]
> The usage of the desktop window class is intended.
Also the fact that you can't fetch it isn't true. The Wrapper class holds all that information you would need.

RECT rct;
GetWindowRect(hWnd, out rct);
GM.Print(rct.Left.ToString() + " - " + rct.Top.ToString() + " - " + rct.Right.ToString() + " - " + 
rct.Bottom.ToString());

always return screen dimension ...

**Comment by YatoDev** [comment]
I know. This is intended. You would need to use the class members to check for the actual position, width and height.
It always applies the desktop screen size at startup but you are still able to set a new size and position through the wrapper class.
This windows does not have a message loop neither is it active

**Comment by YatoDev** [comment]
Everything fixed. But transparency does not work. Feel free to help to change this
