### ISSUE TITLE
How to close properly

### ISSUE THREAD

**Issue by Yothri** [YatoDev/DirectXOverlay#3]
Hi,

Your Renderer and Overlay is really nice, but how to close the Overlay Window properly?
I also tried to use a normal WinForms Form and pass the Handle into the Renderer's Constructor.. that however worked pretty well. I open the Form with Show() instead of ShowDialog() and make a while loop until form.IsDisposed is called. But that however crashs with a NullReferenceException when the Renderer wants to call Finalize... There is no proper way to close right now is there?

Edit: I made a change to the Renderer... I removed the destructor, implemented IDisposable, moved the stuff that was in the destructor into Dispose() method and checking the stuff that was moved for null reference.

Now if I close the form, it calls dispose and disposes all objects as expected without crash.

**Comment by Yothri** [comment]
That is, imo not the proper way of doing it, but I already solved this by Disposing everything before closing. Thanks anyways. There is also a lot of mistakes with colors... The ranges are from 0-1f, not 0-255f anymore. At least in the latest SharpDX binaries. Had to change them... And transparency when drawing for example a filled rectangle doesnt work.

**Comment by YatoDev** [comment]
you could try to change the AlphaMode to straight.

According the SharpDX documentation colors in both 0 - 255 and 0.f - 1 are fine. maybe check the code of the color constructor or any drawing primitive to get a detailed answer.

The Alpha value was converted to float to support various "hacks" i made with the previous version.

**Comment by Yothri** [comment]
Allright, I am going to check that out :)

**Comment by YatoDev** [comment]
Added the Dispose pattern to any class who needs it. Look at the new source code
