### ISSUE TITLE
Not working on 64bits binary!

### ISSUE THREAD

**Issue by lguilhermee** [YatoDev/DirectXOverlay#4]
Hi bro, its seems that the overlay won't work on 64bits binary. its gives a error createwindows: System.Exception: 'CreateWindowEx failed with error code: 127'

**Comment by bestplay9384** [comment]
He already knows about it, it has been reported in UC thread :)

**Comment by antim01** [comment]
working for me

**Comment by YatoDev** [comment]
It's working now.
I reworked everything. All bugs fixed. 64bit support.
